FROM stefanschmidt1/ci-support-files:Fedora30

# Install windows cross build dependencies
RUN dnf install --assumeyes cmake nasm patch gperf mingw32-gcc mingw32-gcc-c++ mingw64-gcc mingw64-gcc-c++ wget bzip2 bison flex yasm

# Build mingw cross-build dependencies for windows build
#RUN cd /; git clone https://github.com/vtorri/ewpi.git
#RUN cd /ewpi; gcc -std=c99 -o ewpi ewpi.c ewpi_map.c
#RUN cd /ewpi; ./ewpi --prefix=/ewpi-64-install --jobs=2 --clean
