FROM fedora:29

# Install
RUN dnf update --assumeyes
RUN dnf install --assumeyes bullet-devel libpng-devel libjpeg-turbo-devel gstreamer1-devel gstreamer1-plugins-base-devel zlib-devel luajit-devel libtiff-devel openssl-devel libcurl-devel dbus-devel dbus-x11 glibc-devel fontconfig-devel freetype-devel fribidi-devel pulseaudio-libs-devel libsndfile-devel libX11-devel libXau-devel libXcomposite-devel libXdamage-devel libXdmcp-devel libXext-devel libXfixes-devel libXinerama-devel libXrandr-devel libXrender-devel libXScrnSaver-devel libXtst-devel libXcursor-devel libXp-devel libXi-devel mesa-libGL-devel giflib-devel libmount-devel libblkid-devel systemd-devel poppler-cpp-devel poppler-devel LibRaw-devel libspectre-devel librsvg2-devel autoconf automake gcc gcc-c++ gettext-devel findutils tar xz libtool make meson ccache git

# Install wayland build dependencies
RUN dnf install --assumeyes wayland-protocols-devel libwayland-client libwayland-server libinput-devel libdrm-devel libxkbcommon-devel uuid-devel wayland-devel mesa-libgbm-devel libxkbcommon-x11-devel mesa-libEGL-devel egl-wayland mesa-libwayland-egl mesa-libwayland-egl-devel

# Install misc build dependencies
RUN dnf install --assumeyes lz4-devel harfbuzz-devel libXpresent-devel libwebp-devel hyphen-devel lua-devel tslib-devel pixman-devel libvncserver-devel SDL2-devel openjpeg2-devel avahi-devel alsa-lib-devel ibus-devel scim-devel gnutls-devel libgcrypt-devel gstreamer-devel gstreamer-plugins-base-devel lcov

# Install windows cross build dependencies
RUN dnf install --assumeyes cmake nasm patch gperf mingw32-gcc mingw32-gcc-c++ mingw64-gcc mingw64-gcc-c++ wget bzip2 efl-devel

# Build mingw cross-build dependencies for windows build
#RUN git clone https://github.com/vtorri/ewpi.git
#RUN cd ewpi; gcc -std=c99 -o ewpi ewpi.c ewpi_map.c
#RUN cd ewpi; ./ewpi /root/EFL/ewpi_64 x86_64-w64-mingw32 1

# Fetch data for exactness run during image creation and only update during builds
RUN git clone https://git.enlightenment.org/tools/exactness-elm-data.git

# Setup machine to be usable with dbus-daemon
RUN systemd-machine-id-setup
