FROM stefanschmidt1/ci-support-files:Fedora30

RUN dnf install --assumeyes cmake nasm patch gperf wget bzip2 bison flex yasm
# Newer mingw-gcc (9.1), header files (6.0), etc needed from rawhide
RUN dnf install fedora-repos-rawhide -y && dnf --disablerepo=* --enablerepo=rawhide --releasever=31 install -y mingw32-gcc mingw32-gcc-c++ mingw64-gcc mingw64-gcc-c++ mingw64-pkg-config

# Build mingw cross-build dependencies for windows build
RUN cd /; \
	git clone https://github.com/vtorri/ewpi.git; \
	cd /ewpi; \
	git checkout 5eaff6e068cd69aa3702dfbe4b7c54790386e286 -b known-working; \
	sed -i -e 's/log 2>&1/make.log 2>&1 || true/g' packages/lz4/install.sh; \
	gcc -std=c99 -o ewpi ewpi.c ewpi_map.c; \
	./ewpi --prefix=/ewpi-64-install --jobs=2
